// https://github.com/Butjok/CommandLine
// This file was automatically generated by CommandLine/Editor/GenerateTokens.cs

namespace Butjok.CommandLine
{
    public enum Token
    {
        Asterisk = 2,
        Comma = 1,
        DoubleAmpersand = 3,
        DoubleVerticalBar = 4,
        Exclamation = 5,
        False = 6,
        Float2 = 7,
        Float3 = 8,
        ForwardSlash = 9,
        Identifier = 23,
        Int2 = 10,
        Int3 = 11,
        Integer = 24,
        LeftParenthesis = 12,
        LeftSquareBracket = 13,
        Minus = 14,
        Null = 15,
        Percent = 16,
        Plus = 17,
        Real = 25,
        Rgb = 18,
        RightParenthesis = 19,
        RightSquareBracket = 20,
        String = 26,
        Tilde = 22,
        True = 21,
        Whitespace = 27,
    }
}
