//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/butjok/Documents/GitHub/Wars5/Assets/CommandLine/CommandLine.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class CommandLineLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Enum=1, Comma=2, Asterisk=3, DoubleAmpersand=4, DoubleVerticalBar=5, Exclamation=6, 
		False=7, Float2=8, Float3=9, ForwardSlash=10, Int2=11, Int3=12, LeftParenthesis=13, 
		LeftSquareBracket=14, Minus=15, Null=16, Percent=17, Plus=18, Rgb=19, 
		RightParenthesis=20, RightSquareBracket=21, True=22, Tilde=23, Identifier=24, 
		Integer=25, Real=26, String=27, Whitespace=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"Enum", "Comma", "Asterisk", "DoubleAmpersand", "DoubleVerticalBar", "Exclamation", 
		"False", "Float2", "Float3", "ForwardSlash", "Int2", "Int3", "LeftParenthesis", 
		"LeftSquareBracket", "Minus", "Null", "Percent", "Plus", "Rgb", "RightParenthesis", 
		"RightSquareBracket", "True", "Tilde", "Identifier", "Integer", "Real", 
		"String", "Whitespace", "INT"
	};


	public CommandLineLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CommandLineLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'enum'", "','", "'*'", "'&&'", "'||'", "'!'", "'false'", "'float2'", 
		"'float3'", "'/'", "'int2'", "'int3'", "'('", "'['", "'-'", "'null'", 
		"'%'", "'+'", "'rgb'", "')'", "']'", "'true'", "'~'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Enum", "Comma", "Asterisk", "DoubleAmpersand", "DoubleVerticalBar", 
		"Exclamation", "False", "Float2", "Float3", "ForwardSlash", "Int2", "Int3", 
		"LeftParenthesis", "LeftSquareBracket", "Minus", "Null", "Percent", "Plus", 
		"Rgb", "RightParenthesis", "RightSquareBracket", "True", "Tilde", "Identifier", 
		"Integer", "Real", "String", "Whitespace"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CommandLine.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CommandLineLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1E', '\xCA', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', 
		'\a', '\x19', '\x8F', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\x92', 
		'\v', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\a', '\x19', 
		'\x97', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\x9A', '\v', '\x19', 
		'\a', '\x19', '\x9C', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\x9F', 
		'\v', '\x19', '\x3', '\x1A', '\x5', '\x1A', '\xA2', '\n', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x5', '\x1B', '\xA7', '\n', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x5', '\x1B', 
		'\xB2', '\n', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\a', '\x1C', '\xB8', '\n', '\x1C', '\f', '\x1C', '\xE', '\x1C', 
		'\xBB', '\v', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x6', 
		'\x1D', '\xC0', '\n', '\x1D', '\r', '\x1D', '\xE', '\x1D', '\xC1', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x6', '\x1E', '\xC7', '\n', '\x1E', 
		'\r', '\x1E', '\xE', '\x1E', '\xC8', '\x2', '\x2', '\x1F', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', 
		'\x39', '\x1E', ';', '\x2', '\x3', '\x2', '\b', '\x5', '\x2', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\t', '\x2', '$', '$', '^', '^', '\x64', 
		'\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 'v', '\x5', '\x2', '\x2', '!', 
		'$', '$', '^', '^', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x3', '\x2', '\x32', ';', '\x2', '\xD3', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x3', '=', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x42', '\x3', '\x2', '\x2', '\x2', '\a', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\t', '\x46', '\x3', '\x2', '\x2', '\x2', '\v', 'I', 
		'\x3', '\x2', '\x2', '\x2', '\r', 'L', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'N', '\x3', '\x2', '\x2', '\x2', '\x11', 'T', '\x3', '\x2', '\x2', '\x2', 
		'\x13', '[', '\x3', '\x2', '\x2', '\x2', '\x15', '\x62', '\x3', '\x2', 
		'\x2', '\x2', '\x17', '\x64', '\x3', '\x2', '\x2', '\x2', '\x19', 'i', 
		'\x3', '\x2', '\x2', '\x2', '\x1B', 'n', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'p', '\x3', '\x2', '\x2', '\x2', '\x1F', 'r', '\x3', '\x2', '\x2', '\x2', 
		'!', 't', '\x3', '\x2', '\x2', '\x2', '#', 'y', '\x3', '\x2', '\x2', '\x2', 
		'%', '{', '\x3', '\x2', '\x2', '\x2', '\'', '}', '\x3', '\x2', '\x2', 
		'\x2', ')', '\x81', '\x3', '\x2', '\x2', '\x2', '+', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x85', '\x3', '\x2', '\x2', '\x2', '/', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '\x35', '\xA6', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\xB3', '\x3', '\x2', '\x2', '\x2', '\x39', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', ';', '\xC6', '\x3', '\x2', '\x2', '\x2', '=', '>', 
		'\a', 'g', '\x2', '\x2', '>', '?', '\a', 'p', '\x2', '\x2', '?', '@', 
		'\a', 'w', '\x2', '\x2', '@', '\x41', '\a', 'o', '\x2', '\x2', '\x41', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', '.', '\x2', '\x2', 
		'\x43', '\x6', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\a', ',', 
		'\x2', '\x2', '\x45', '\b', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', 
		'(', '\x2', '\x2', 'G', 'H', '\a', '(', '\x2', '\x2', 'H', '\n', '\x3', 
		'\x2', '\x2', '\x2', 'I', 'J', '\a', '~', '\x2', '\x2', 'J', 'K', '\a', 
		'~', '\x2', '\x2', 'K', '\f', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', 
		'#', '\x2', '\x2', 'M', '\xE', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\a', 
		'h', '\x2', '\x2', 'O', 'P', '\a', '\x63', '\x2', '\x2', 'P', 'Q', '\a', 
		'n', '\x2', '\x2', 'Q', 'R', '\a', 'u', '\x2', '\x2', 'R', 'S', '\a', 
		'g', '\x2', '\x2', 'S', '\x10', '\x3', '\x2', '\x2', '\x2', 'T', 'U', 
		'\a', 'h', '\x2', '\x2', 'U', 'V', '\a', 'n', '\x2', '\x2', 'V', 'W', 
		'\a', 'q', '\x2', '\x2', 'W', 'X', '\a', '\x63', '\x2', '\x2', 'X', 'Y', 
		'\a', 'v', '\x2', '\x2', 'Y', 'Z', '\a', '\x34', '\x2', '\x2', 'Z', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', 'h', '\x2', '\x2', '\\', 
		']', '\a', 'n', '\x2', '\x2', ']', '^', '\a', 'q', '\x2', '\x2', '^', 
		'_', '\a', '\x63', '\x2', '\x2', '_', '`', '\a', 'v', '\x2', '\x2', '`', 
		'\x61', '\a', '\x35', '\x2', '\x2', '\x61', '\x14', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x63', '\a', '\x31', '\x2', '\x2', '\x63', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x64', '\x65', '\a', 'k', '\x2', '\x2', '\x65', 
		'\x66', '\a', 'p', '\x2', '\x2', '\x66', 'g', '\a', 'v', '\x2', '\x2', 
		'g', 'h', '\a', '\x34', '\x2', '\x2', 'h', '\x18', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'j', '\a', 'k', '\x2', '\x2', 'j', 'k', '\a', 'p', '\x2', 
		'\x2', 'k', 'l', '\a', 'v', '\x2', '\x2', 'l', 'm', '\a', '\x35', '\x2', 
		'\x2', 'm', '\x1A', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\a', '*', '\x2', 
		'\x2', 'o', '\x1C', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', ']', '\x2', 
		'\x2', 'q', '\x1E', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '/', '\x2', 
		'\x2', 's', ' ', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 'p', '\x2', 
		'\x2', 'u', 'v', '\a', 'w', '\x2', '\x2', 'v', 'w', '\a', 'n', '\x2', 
		'\x2', 'w', 'x', '\a', 'n', '\x2', '\x2', 'x', '\"', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\a', '\'', '\x2', '\x2', 'z', '$', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '-', '\x2', '\x2', '|', '&', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\a', 't', '\x2', '\x2', '~', '\x7F', '\a', 'i', '\x2', 
		'\x2', '\x7F', '\x80', '\a', '\x64', '\x2', '\x2', '\x80', '(', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x82', '\a', '+', '\x2', '\x2', '\x82', 
		'*', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\a', '_', '\x2', '\x2', 
		'\x84', ',', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\a', 'v', '\x2', 
		'\x2', '\x86', '\x87', '\a', 't', '\x2', '\x2', '\x87', '\x88', '\a', 
		'w', '\x2', '\x2', '\x88', '\x89', '\a', 'g', '\x2', '\x2', '\x89', '.', 
		'\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', '\x80', '\x2', '\x2', 
		'\x8B', '\x30', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x90', '\t', '\x2', 
		'\x2', '\x2', '\x8D', '\x8F', '\t', '\x3', '\x2', '\x2', '\x8E', '\x8D', 
		'\x3', '\x2', '\x2', '\x2', '\x8F', '\x92', '\x3', '\x2', '\x2', '\x2', 
		'\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x92', '\x90', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\a', '\x30', '\x2', '\x2', 
		'\x94', '\x98', '\t', '\x2', '\x2', '\x2', '\x95', '\x97', '\t', '\x3', 
		'\x2', '\x2', '\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x9A', 
		'\x3', '\x2', '\x2', '\x2', '\x98', '\x96', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9C', '\x3', '\x2', 
		'\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x93', 
		'\x3', '\x2', '\x2', '\x2', '\x9C', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\x9D', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\x32', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9D', 
		'\x3', '\x2', '\x2', '\x2', '\xA0', '\xA2', '\a', '/', '\x2', '\x2', '\xA1', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xA2', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x5', 
		';', '\x1E', '\x2', '\xA4', '\x34', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA7', '\a', '/', '\x2', '\x2', '\xA6', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\xA9', '\x5', ';', '\x1E', '\x2', '\xA9', 
		'\xAA', '\a', '\x30', '\x2', '\x2', '\xAA', '\xAB', '\x5', ';', '\x1E', 
		'\x2', '\xAB', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', 
		'\x30', '\x2', '\x2', '\xAD', '\xB2', '\x5', ';', '\x1E', '\x2', '\xAE', 
		'\xAF', '\x5', ';', '\x1E', '\x2', '\xAF', '\xB0', '\a', '\x30', '\x2', 
		'\x2', '\xB0', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xA8', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xB1', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xB2', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB9', '\a', '$', '\x2', '\x2', '\xB4', '\xB5', '\a', 
		'^', '\x2', '\x2', '\xB5', '\xB8', '\t', '\x4', '\x2', '\x2', '\xB6', 
		'\xB8', '\n', '\x5', '\x2', '\x2', '\xB7', '\xB4', '\x3', '\x2', '\x2', 
		'\x2', '\xB7', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBB', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\a', 
		'$', '\x2', '\x2', '\xBD', '\x38', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xC0', '\t', '\x6', '\x2', '\x2', '\xBF', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\xC0', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC2', 
		'\xC3', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\b', '\x1D', '\x2', 
		'\x2', '\xC4', ':', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC7', '\t', 
		'\a', '\x2', '\x2', '\xC6', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', '<', '\x3', 
		'\x2', '\x2', '\x2', '\r', '\x2', '\x90', '\x98', '\x9D', '\xA1', '\xA6', 
		'\xB1', '\xB7', '\xB9', '\xC1', '\xC8', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
