//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/butjok/Documents/GitHub/Wars5/Assets/CommandLine/CommandLine.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class CommandLineLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Whitespace=1, BlockComment=2, LineComment=3, Semicolon=4, Enum=5, Asterisk=6, 
		DoubleAmpersand=7, DoubleVerticalBar=8, Exclamation=9, False=10, Float2=11, 
		Float3=12, ForwardSlash=13, Int2=14, Int3=15, LeftParenthesis=16, Minus=17, 
		Null=18, Percent=19, Plus=20, Rgb=21, RightParenthesis=22, True=23, Tilde=24, 
		Identifier=25, Integer=26, Real=27, String=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"Whitespace", "BlockComment", "LineComment", "Semicolon", "Enum", "Asterisk", 
		"DoubleAmpersand", "DoubleVerticalBar", "Exclamation", "False", "Float2", 
		"Float3", "ForwardSlash", "Int2", "Int3", "LeftParenthesis", "Minus", 
		"Null", "Percent", "Plus", "Rgb", "RightParenthesis", "True", "Tilde", 
		"Identifier", "Integer", "Real", "String", "INT"
	};


	public CommandLineLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CommandLineLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, "';'", "'enum'", "'*'", "'&&'", "'||'", "'!'", 
		"'false'", "'float2'", "'float3'", "'/'", "'int2'", "'int3'", "'('", "'-'", 
		"'null'", "'%'", "'+'", "'rgb'", "')'", "'true'", "'~'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Whitespace", "BlockComment", "LineComment", "Semicolon", "Enum", 
		"Asterisk", "DoubleAmpersand", "DoubleVerticalBar", "Exclamation", "False", 
		"Float2", "Float3", "ForwardSlash", "Int2", "Int3", "LeftParenthesis", 
		"Minus", "Null", "Percent", "Plus", "Rgb", "RightParenthesis", "True", 
		"Tilde", "Identifier", "Integer", "Real", "String"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CommandLine.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CommandLineLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1E', '\xDF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x6', '\x2', '?', 
		'\n', '\x2', '\r', '\x2', '\xE', '\x2', '@', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 'I', 
		'\n', '\x3', '\f', '\x3', '\xE', '\x3', 'L', '\v', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 'W', '\n', '\x4', 
		'\f', '\x4', '\xE', '\x4', 'Z', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\a', '\x1A', 
		'\xAB', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\xAE', '\v', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\a', '\x1A', '\xB3', '\n', 
		'\x1A', '\f', '\x1A', '\xE', '\x1A', '\xB6', '\v', '\x1A', '\a', '\x1A', 
		'\xB8', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\xBB', '\v', '\x1A', 
		'\x3', '\x1B', '\x5', '\x1B', '\xBE', '\n', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1C', '\x5', '\x1C', '\xC3', '\n', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x5', '\x1C', '\xCE', '\n', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\a', 
		'\x1D', '\xD4', '\n', '\x1D', '\f', '\x1D', '\xE', '\x1D', '\xD7', '\v', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x6', '\x1E', '\xDC', 
		'\n', '\x1E', '\r', '\x1E', '\xE', '\x1E', '\xDD', '\x3', 'J', '\x2', 
		'\x1F', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', 
		'-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', 
		'\x37', '\x1D', '\x39', '\x1E', ';', '\x2', '\x3', '\x2', '\t', '\x5', 
		'\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', '\f', '\f', 
		'\xF', '\xF', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\t', '\x2', '$', '$', '^', '^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 
		't', 'v', 'v', '\x5', '\x2', '\x2', '!', '$', '$', '^', '^', '\x3', '\x2', 
		'\x32', ';', '\x2', '\xEA', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '>', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\a', 'R', '\x3', '\x2', '\x2', '\x2', 
		'\t', ']', '\x3', '\x2', '\x2', '\x2', '\v', '_', '\x3', '\x2', '\x2', 
		'\x2', '\r', '\x64', '\x3', '\x2', '\x2', '\x2', '\xF', '\x66', '\x3', 
		'\x2', '\x2', '\x2', '\x11', 'i', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'l', '\x3', '\x2', '\x2', '\x2', '\x15', 'n', '\x3', '\x2', '\x2', '\x2', 
		'\x17', 't', '\x3', '\x2', '\x2', '\x2', '\x19', '{', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x82', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\x89', '\x3', '\x2', '\x2', '\x2', '!', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '#', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '%', '\x92', '\x3', '\x2', '\x2', '\x2', '\'', '\x97', '\x3', '\x2', 
		'\x2', '\x2', ')', '\x99', '\x3', '\x2', '\x2', '\x2', '+', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '-', '\x9F', '\x3', '\x2', '\x2', '\x2', '/', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\xA8', '\x3', '\x2', '\x2', '\x2', '\x35', '\xBD', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\xC2', '\x3', '\x2', '\x2', '\x2', '\x39', '\xCF', 
		'\x3', '\x2', '\x2', '\x2', ';', '\xDB', '\x3', '\x2', '\x2', '\x2', '=', 
		'?', '\t', '\x2', '\x2', '\x2', '>', '=', '\x3', '\x2', '\x2', '\x2', 
		'?', '@', '\x3', '\x2', '\x2', '\x2', '@', '>', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\x42', '\x43', '\b', '\x2', '\x2', '\x2', '\x43', '\x4', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\a', '\x31', '\x2', '\x2', 
		'\x45', '\x46', '\a', ',', '\x2', '\x2', '\x46', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'G', 'I', '\v', '\x2', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'L', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x3', '\x2', '\x2', 
		'\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 'K', 'M', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', ',', '\x2', 
		'\x2', 'N', 'O', '\a', '\x31', '\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'P', 'Q', '\b', '\x3', '\x2', '\x2', 'Q', '\x6', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'S', '\a', '\x31', '\x2', '\x2', 'S', 'T', '\a', '\x31', 
		'\x2', '\x2', 'T', 'X', '\x3', '\x2', '\x2', '\x2', 'U', 'W', '\n', '\x3', 
		'\x2', '\x2', 'V', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'Z', '\x3', '\x2', 
		'\x2', '\x2', 'X', 'V', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x3', '\x2', 
		'\x2', '\x2', 'Y', '[', '\x3', '\x2', '\x2', '\x2', 'Z', 'X', '\x3', '\x2', 
		'\x2', '\x2', '[', '\\', '\b', '\x4', '\x2', '\x2', '\\', '\b', '\x3', 
		'\x2', '\x2', '\x2', ']', '^', '\a', '=', '\x2', '\x2', '^', '\n', '\x3', 
		'\x2', '\x2', '\x2', '_', '`', '\a', 'g', '\x2', '\x2', '`', '\x61', '\a', 
		'p', '\x2', '\x2', '\x61', '\x62', '\a', 'w', '\x2', '\x2', '\x62', '\x63', 
		'\a', 'o', '\x2', '\x2', '\x63', '\f', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\a', ',', '\x2', '\x2', '\x65', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'\x66', 'g', '\a', '(', '\x2', '\x2', 'g', 'h', '\a', '(', '\x2', '\x2', 
		'h', '\x10', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '~', '\x2', '\x2', 
		'j', 'k', '\a', '~', '\x2', '\x2', 'k', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\a', '#', '\x2', '\x2', 'm', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\a', 'h', '\x2', '\x2', 'o', 'p', '\a', '\x63', '\x2', '\x2', 
		'p', 'q', '\a', 'n', '\x2', '\x2', 'q', 'r', '\a', 'u', '\x2', '\x2', 
		'r', 's', '\a', 'g', '\x2', '\x2', 's', '\x16', '\x3', '\x2', '\x2', '\x2', 
		't', 'u', '\a', 'h', '\x2', '\x2', 'u', 'v', '\a', 'n', '\x2', '\x2', 
		'v', 'w', '\a', 'q', '\x2', '\x2', 'w', 'x', '\a', '\x63', '\x2', '\x2', 
		'x', 'y', '\a', 'v', '\x2', '\x2', 'y', 'z', '\a', '\x34', '\x2', '\x2', 
		'z', '\x18', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', 'h', '\x2', '\x2', 
		'|', '}', '\a', 'n', '\x2', '\x2', '}', '~', '\a', 'q', '\x2', '\x2', 
		'~', '\x7F', '\a', '\x63', '\x2', '\x2', '\x7F', '\x80', '\a', 'v', '\x2', 
		'\x2', '\x80', '\x81', '\a', '\x35', '\x2', '\x2', '\x81', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x83', '\a', '\x31', '\x2', '\x2', '\x83', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', 'k', '\x2', 
		'\x2', '\x85', '\x86', '\a', 'p', '\x2', '\x2', '\x86', '\x87', '\a', 
		'v', '\x2', '\x2', '\x87', '\x88', '\a', '\x34', '\x2', '\x2', '\x88', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', 'k', '\x2', 
		'\x2', '\x8A', '\x8B', '\a', 'p', '\x2', '\x2', '\x8B', '\x8C', '\a', 
		'v', '\x2', '\x2', '\x8C', '\x8D', '\a', '\x35', '\x2', '\x2', '\x8D', 
		' ', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '*', '\x2', '\x2', 
		'\x8F', '\"', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\a', '/', '\x2', 
		'\x2', '\x91', '$', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', 
		'p', '\x2', '\x2', '\x93', '\x94', '\a', 'w', '\x2', '\x2', '\x94', '\x95', 
		'\a', 'n', '\x2', '\x2', '\x95', '\x96', '\a', 'n', '\x2', '\x2', '\x96', 
		'&', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\a', '\'', '\x2', '\x2', 
		'\x98', '(', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '-', '\x2', 
		'\x2', '\x9A', '*', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', 
		't', '\x2', '\x2', '\x9C', '\x9D', '\a', 'i', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', '\x64', '\x2', '\x2', '\x9E', ',', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', '+', '\x2', '\x2', '\xA0', '.', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\xA2', '\a', 'v', '\x2', '\x2', '\xA2', '\xA3', '\a', 't', '\x2', 
		'\x2', '\xA3', '\xA4', '\a', 'w', '\x2', '\x2', '\xA4', '\xA5', '\a', 
		'g', '\x2', '\x2', '\xA5', '\x30', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', '\x80', '\x2', '\x2', '\xA7', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xAC', '\t', '\x4', '\x2', '\x2', '\xA9', '\xAB', '\t', 
		'\x5', '\x2', '\x2', '\xAA', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xB9', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB0', '\a', '\x30', '\x2', '\x2', '\xB0', '\xB4', '\t', '\x4', '\x2', 
		'\x2', '\xB1', '\xB3', '\t', '\x5', '\x2', '\x2', '\xB2', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\x3', '\x2', '\x2', 
		'\x2', '\xB5', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB4', '\x3', 
		'\x2', '\x2', '\x2', '\xB7', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xB9', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xBE', '\a', '/', '\x2', '\x2', '\xBD', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBD', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\xC0', '\x5', ';', '\x1E', '\x2', '\xC0', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC3', '\a', '/', '\x2', 
		'\x2', '\xC2', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC3', '\x3', 
		'\x2', '\x2', '\x2', '\xC3', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xC5', '\x5', ';', '\x1E', '\x2', '\xC5', '\xC6', '\a', '\x30', '\x2', 
		'\x2', '\xC6', '\xC7', '\x5', ';', '\x1E', '\x2', '\xC7', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC9', '\a', '\x30', '\x2', '\x2', '\xC9', 
		'\xCE', '\x5', ';', '\x1E', '\x2', '\xCA', '\xCB', '\x5', ';', '\x1E', 
		'\x2', '\xCB', '\xCC', '\a', '\x30', '\x2', '\x2', '\xCC', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\xC8', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCE', '\x38', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD5', '\a', 
		'$', '\x2', '\x2', '\xD0', '\xD1', '\a', '^', '\x2', '\x2', '\xD1', '\xD4', 
		'\t', '\x6', '\x2', '\x2', '\xD2', '\xD4', '\n', '\a', '\x2', '\x2', '\xD3', 
		'\xD0', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\xD4', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD3', '\x3', 
		'\x2', '\x2', '\x2', '\xD5', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD6', 
		'\xD8', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xD8', '\xD9', '\a', '$', '\x2', '\x2', '\xD9', ':', '\x3', '\x2', 
		'\x2', '\x2', '\xDA', '\xDC', '\t', '\b', '\x2', '\x2', '\xDB', '\xDA', 
		'\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', '\x2', 
		'\xDD', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', '\x2', 
		'\x2', '\x2', '\xDE', '<', '\x3', '\x2', '\x2', '\x2', '\xF', '\x2', '@', 
		'J', 'X', '\xAC', '\xB4', '\xB9', '\xBD', '\xC2', '\xCD', '\xD3', '\xD5', 
		'\xDD', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
